"""Self-contained HTML report generator for behavioral session analytics.

The generated HTML:
  - Is a single file (no external dependencies, CDN, or font requests).
  - Embeds all charts as base64 PNG data URIs.
  - Uses inline CSS only — no JavaScript, no frameworks.
  - Renders cleanly in any modern browser and on GitHub Pages.

Design: string formatting rather than a template engine so the reporting
layer has zero extra dependencies (Jinja2, etc. are not required).
"""

from __future__ import annotations

import base64
from dataclasses import asdict
from typing import Any, Dict, List, Optional

from src.reporting.metrics import SessionMetrics


# ── CSS (dark-theme, portfolio-friendly) ──────────────────────────────────────

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
  background: #0D1117; color: #C9D1D9;
  max-width: 1100px; margin: 0 auto; padding: 32px 24px;
}
h1 { font-size: 1.7rem; color: #58A6FF; margin-bottom: 4px; }
h2 { font-size: 1.15rem; color: #79C0FF; margin: 28px 0 10px; border-bottom: 1px solid #21262D; padding-bottom: 6px; }
h3 { font-size: 0.95rem; color: #8B949E; margin: 18px 0 8px; }
.subtitle { color: #8B949E; font-size: 0.85rem; margin-bottom: 24px; }
.badge {
  display: inline-block; padding: 3px 10px; border-radius: 12px;
  font-size: 0.78rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;
}
.badge-focused    { background: #1A4731; color: #27AE60; }
.badge-drifting   { background: #4A3800; color: #F1C40F; }
.badge-distracted { background: #4A2000; color: #E67E22; }
.badge-fatigued   { background: #4A0E0E; color: #E74C3C; }
.badge-unreliable { background: #252A2E; color: #95A5A6; }
.grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; }
.card {
  background: #161B22; border: 1px solid #21262D; border-radius: 8px;
  padding: 16px 18px;
}
.card .label { font-size: 0.75rem; color: #8B949E; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
.card .value { font-size: 1.3rem; color: #E6EDF3; font-weight: 600; }
.card .unit  { font-size: 0.75rem; color: #8B949E; margin-left: 4px; }
table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
th { text-align: left; color: #8B949E; font-weight: 500; padding: 8px 12px;
     border-bottom: 1px solid #21262D; white-space: nowrap; }
td { padding: 7px 12px; border-bottom: 1px solid #161B22; color: #C9D1D9; }
tr:hover td { background: #161B22; }
.pct-bar { height: 6px; border-radius: 3px; margin-top: 3px; min-width: 4px; }
img.chart { width: 100%; border-radius: 6px; margin-top: 8px; border: 1px solid #21262D; }
.limitation { background: #161B22; border-left: 3px solid #E67E22; padding: 10px 14px;
              border-radius: 0 4px 4px 0; font-size: 0.82rem; color: #8B949E; margin-top: 10px; }
footer { margin-top: 40px; font-size: 0.75rem; color: #484F58; border-top: 1px solid #21262D; padding-top: 16px; }
"""


def generate_html(
    metrics:     SessionMetrics,
    chart_pngs:  Dict[str, bytes],   # name → PNG bytes
    trial_table: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """Render a complete self-contained HTML report."""
    dom_state = _dominant_state(metrics.engagement)
    badge_cls = f"badge badge-{dom_state}"

    overview_cards = _overview_cards(metrics)
    engagement_section = _engagement_section(metrics)
    signal_section     = _signal_section(metrics)
    stimulus_section   = _stimulus_section(metrics)
    trial_section      = _trial_table(trial_table or [])
    charts_section     = _charts_section(chart_pngs)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Session Report — {metrics.session_id}</title>
  <style>{_CSS}</style>
</head>
<body>

<h1>Behavioral Session Report</h1>
<p class="subtitle">
  Session <code>{metrics.session_id}</code> &nbsp;|&nbsp;
  {metrics.experiment_name} &nbsp;|&nbsp;
  Generated {metrics.generated_at[:19].replace("T", " ")} UTC
</p>

<h2>Session Overview</h2>
{overview_cards}

{engagement_section}
{signal_section}
{charts_section}
{stimulus_section}
{trial_section}

<div class="limitation">
  <strong>Note:</strong> These are approximate behavioral orientation metrics
  derived from a consumer webcam.  They measure where the user was looking and
  their blink patterns — not cognitive engagement or comprehension.
  Frame-rate granularity (~33 ms at 30 FPS) limits reaction-time precision.
  Results should not be used for individual clinical or cognitive assessment.
</div>

<footer>
  Generated by multimodal-response-lab &nbsp;|&nbsp;
  {metrics.n_frames} frames &nbsp;|&nbsp;
  {metrics.n_trials} trials &nbsp;|&nbsp;
  {metrics.n_responses} responses
</footer>

</body>
</html>"""


# ── Section builders ──────────────────────────────────────────────────────────

def _overview_cards(m: SessionMetrics) -> str:
    dur  = f"{m.duration_s:.1f}" if m.duration_s else "—"
    dom  = _dominant_state(m.engagement)
    foc  = f"{m.engagement.focused_fraction * 100:.1f}"
    on_s = f"{m.gaze.on_screen_fraction * 100:.1f}"

    return f"""
<div class="grid-3">
  <div class="card">
    <div class="label">Duration</div>
    <div class="value">{dur}<span class="unit">s</span></div>
  </div>
  <div class="card">
    <div class="label">Frames / Trials</div>
    <div class="value">{m.n_frames}<span class="unit">frames</span>
      &nbsp; {m.n_trials}<span class="unit">trials</span></div>
  </div>
  <div class="card">
    <div class="label">Dominant State</div>
    <div class="value"><span class="badge badge-{dom}">{dom}</span></div>
  </div>
  <div class="card">
    <div class="label">Focused Fraction</div>
    <div class="value">{foc}<span class="unit">%</span></div>
  </div>
  <div class="card">
    <div class="label">On-Screen Fraction</div>
    <div class="value">{on_s}<span class="unit">%</span></div>
  </div>
  <div class="card">
    <div class="label">Mean Eng. Score</div>
    <div class="value">{m.engagement.score_summary.mean:.3f}</div>
  </div>
</div>"""


def _engagement_section(m: SessionMetrics) -> str:
    e = m.engagement
    s = e.score_summary
    rows = [
        ("Mean score",        f"{s.mean:.3f}"),
        ("Std dev",           f"{s.std:.3f}"),
        ("25th / 75th pct",   f"{s.p25:.3f} / {s.p75:.3f}"),
        ("Min / Max",         f"{s.min_val:.3f} / {s.max_val:.3f}"),
        ("Focused",           f"{e.focused_fraction*100:.1f}%"),
        ("Drifting",          f"{e.drifting_fraction*100:.1f}%"),
        ("Distracted",        f"{e.distracted_fraction*100:.1f}%"),
        ("Fatigued",          f"{e.fatigued_fraction*100:.1f}%"),
        ("Unreliable",        f"{e.unreliable_fraction*100:.1f}%"),
    ]
    return f"""
<h2>Engagement Metrics</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  {"".join(f"<tr><td>{r[0]}</td><td>{r[1]}</td></tr>" for r in rows)}
</table>"""


def _signal_section(m: SessionMetrics) -> str:
    g = m.gaze;  h = m.head;  b = m.blink

    rows = [
        ("On-screen fraction",      f"{g.on_screen_fraction*100:.1f}%"),
        ("Gaze H mean ± std",       f"{g.gaze_h_summary.mean:.3f} ± {g.gaze_h_summary.std:.3f}"),
        ("Gaze V mean ± std",       f"{g.gaze_v_summary.mean:.3f} ± {g.gaze_v_summary.std:.3f}"),
        ("Head focused fraction",   f"{h.head_focused_fraction*100:.1f}%"),
        ("Head yaw mean ± std",     f"{h.yaw_summary.mean:.1f}° ± {h.yaw_summary.std:.1f}°"),
        ("Head pitch mean ± std",   f"{h.pitch_summary.mean:.1f}° ± {h.pitch_summary.std:.1f}°"),
        ("Blink rate mean ± std",   f"{b.blink_rate_summary.mean:.1f} ± {b.blink_rate_summary.std:.1f} /min"),
        ("Blink rate range",        f"{b.blink_rate_summary.min_val:.1f} – {b.blink_rate_summary.max_val:.1f} /min"),
        ("Fatigue fraction",        f"{b.fatigue_fraction*100:.1f}%"),
        ("Mean EAR",                f"{b.ear_summary.mean:.3f}"),
    ]
    return f"""
<h2>Signal Channel Summaries</h2>
<table>
  <tr><th>Channel / Metric</th><th>Value</th></tr>
  {"".join(f"<tr><td>{r[0]}</td><td>{r[1]}</td></tr>" for r in rows)}
</table>"""


def _stimulus_section(m: SessionMetrics) -> str:
    if not m.stimulus_types:
        return ""

    header = ("<tr><th>Type</th><th>Trials</th><th>Hit%</th>"
              "<th>Mean latency</th><th>Baseline score</th>"
              "<th>During score</th><th>Score Δ</th><th>Recovery</th></tr>")
    rows = []
    for stype, st in sorted(m.stimulus_types.items()):
        lat = f"{st.mean_latency_ms:.0f} ms" if st.mean_latency_ms else "—"
        rec = f"{st.mean_recovery_s:.1f} s"   if st.mean_recovery_s  else "—"
        delta_col = "#27AE60" if st.score_delta >= 0 else "#E74C3C"
        rows.append(
            f"<tr><td>{stype}</td><td>{st.n_trials}</td>"
            f"<td>{st.hit_rate*100:.0f}%</td><td>{lat}</td>"
            f"<td>{st.mean_baseline_score:.3f}</td>"
            f"<td>{st.mean_during_score:.3f}</td>"
            f"<td style='color:{delta_col}'>{st.score_delta:+.3f}</td>"
            f"<td>{rec}</td></tr>"
        )
    return f"""
<h2>Per-Stimulus Type Analysis</h2>
<p style="font-size:0.8rem;color:#8B949E;margin-bottom:8px">
  Score Δ = mean during − mean baseline.  Negative = stimulus was disruptive.
</p>
<table>
  {header}
  {"".join(rows)}
</table>"""


def _trial_table(trials: List[Dict[str, Any]]) -> str:
    if not trials:
        return ""
    header = ("<tr><th>#</th><th>Stimulus</th><th>Type</th>"
              "<th>Latency</th><th>Response</th><th>Hit</th>"
              "<th>Baseline</th><th>During</th><th>Recovery</th></tr>")
    rows = []
    for t in trials:
        lat  = f"{t['reaction_latency_ms']:.0f} ms" if t.get("reaction_latency_ms") else "—"
        rtype = t.get("response_type") or "—"
        rec   = f"{t['recovery_s']:.1f} s" if t.get("recovery_s") else "—"
        hit_s = "✓" if t.get("hit") else "—"
        rows.append(
            f"<tr><td>{t['trial_index']}</td><td>{t['stimulus_id']}</td>"
            f"<td>{t['stimulus_type']}</td><td>{lat}</td><td>{rtype}</td>"
            f"<td>{hit_s}</td><td>{t.get('baseline_score', 0):.3f}</td>"
            f"<td>{t.get('during_score', 0):.3f}</td><td>{rec}</td></tr>"
        )
    return f"""
<h2>Trial Summaries</h2>
<table>
  {header}
  {"".join(rows)}
</table>"""


def _charts_section(chart_pngs: Dict[str, bytes]) -> str:
    if not chart_pngs:
        return ""

    titles = {
        "engagement_timeline": "Engagement Score Timeline",
        "state_distribution":  "State Distribution",
        "signal_channels":     "Signal Channels Over Time",
        "stimulus_comparison": "Stimulus: Baseline vs. During Score",
        "reaction_latency":    "Reaction Latency by Stimulus Type",
    }

    items = []
    for name, png in chart_pngs.items():
        b64  = base64.b64encode(png).decode("ascii")
        ttl  = titles.get(name, name.replace("_", " ").title())
        items.append(f"""
  <div>
    <h3>{ttl}</h3>
    <img class="chart" src="data:image/png;base64,{b64}" alt="{ttl}">
  </div>""")

    return f"""
<h2>Charts</h2>
{"".join(items)}"""


# ── Utility ───────────────────────────────────────────────────────────────────

def _dominant_state(e) -> str:
    """Return the state with the highest fraction (excluding unreliable)."""
    candidates = {
        "focused":    e.focused_fraction,
        "drifting":   e.drifting_fraction,
        "distracted": e.distracted_fraction,
        "fatigued":   e.fatigued_fraction,
    }
    dom = max(candidates, key=candidates.get)
    # Fall back to unreliable if everything is very low
    if candidates[dom] < 0.10 and e.unreliable_fraction > 0.5:
        return "unreliable"
    return dom
